#!/bin/sh

# Feed a music directory into mpv and present choice to shuffle the music within 

if [ -n "$WAYLAND_DISPLAY" ]; then
	dmenu=dmenu-wl
else
	dmenu=dmenu
	#dmenu=mydmenu
fi

killmusic() {
	for pid in $(pgrep musicbox); do pkill -P $pid; done
	exit 1
}

playlists() { 
	[ -z "$choice" ] && exit 1
	case "$choice" in
		"playlist0")  playlist="https://www.youtube.com/playlist?list=xxx";;
		"playlist1")  playlist="https://www.youtube.com/playlist?list=xxx";;
		"playlist2")  playlist="https://www.youtube.com/playlist?list=xxx";;
	esac
}

fetchAlbum() { 
	DIR="$HOME/Music"
	allMusic="All of it"
	killit="Kill it"

	choice="$(find "$DIR" -type d -printf '%P\n' 2>/dev/null | \
		sort | \
		sed "1s/.*/$allMusic/; $ a playlist0\nplaylist1\nplaylist2\n$killit" | \
		$dmenu -i -l 8 -p "___   Select an album: ")" || exit 1

	# Kill the music
	[ "$choice" = "$killit" ] && killmusic

	# Get music directory
	playlist="$DIR/$choice"
	[ "$choice" = "$allMusic" ] && playlist="$DIR"

	# Fetch YouTube playlist
	[ ! -d "$playlist" ] && playlists

	# Choose to shuffle
	shuffle_choice=$(printf "Yes\\nNo" | $dmenu -i -p "Shuffle?") || exit 1
	[ "$shuffle_choice" = "Yes" ] && shuffle="--shuffle"

	mpv --ytdl-raw-options-append=cookies-from-browser=firefox \
		--loop-file=no $shuffle "$playlist"
}

fetchAlbum
